// Blocks
require("testbomb")
require("blocks/crystal-conveyor")
require("blocks/godturrets")
require("blocks/surge-reactor")
require("blocks/surge-battery")
//require("blocks/cryogem-dissipator")
//require("blocks/cryocentrifuge")
//require("blocks/multimelter")
require("blocks/multipyra")
require("blocks/heavy-coal-processor")
require("blocks/omnijunction")
require("blocks/commandcenter")
// V5 unit scripts commented out for archival purposes
// Regular Units
//require("mechs/lambdaship")
//require("units/schadenfreude")
//require("units/spiker")
//require("units/overdriver")
//require("units/fixer")
//require("units/beelzebub")
// Spore content
require("blocks/spore-blocks")
require("blocks/water-decorruptor")
//require("units/spore-fortress")
//require("units/spore-bosses")
//require("units/spore-bombs")
// Ancient Content
require("blocks/ancientrefinery")
require("blocks/ancients")
//require("units/ancient-scavenger")
//require("units/ancient-assembler")
//require("units/ancient-zapper")
//require("units/ancient-widowmine")
//require("units/ancient-pawn")
//require("units/ancient-grunt")
//require("units/ancient-warrior")
//require("units/ancient-guardian")
//require("units/ancient-sniper")
//require("units/ancient-engineer")
//require("units/ancient-air-units")
//require("units/basilisk")
//require("units/spoilers")
//require("mechs/illithid")
require("blocks/vanillaammo")

